version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"

  order-service:
    build:
      context: .
      dockerfile: order.microservice/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "3001:80"
      - "3031:443"
    restart: on-failure:5 # always
    depends_on:
      - "rabbitmq"

  customer-service:
    build:
      context: .
      dockerfile: customer.microservice/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "3002:80"
      - "3032:443"  
    restart: on-failure:5 # always
    depends_on:
      - "rabbitmq"